/** Kitaptaki şiir başlıkları (sıra ile) */
export const POEM_TITLES = [
  "Zeytin Ağacı",
  "Harman",
  "Kahverengi",
  "El alem",
  "Bir Kuşak Geliyor",
  "Sessiz Camia",
  "Nar",
  "Bizim Şiirin Kızı",
  "Makber",
  "İyi Sonsuzluklar",
  "Bıçak Altı",
  "Bizim Kuşlar Mezarlıklarda Durmazlar",
  "Kara Para",
  "ahh Galata",
  "Sihirbaz",
  "Yine Gündüz",
  "Tükenmişliğin Belirtileri",
  "Hesabını Yapmak Kaybını Zamanın",
  "Yorgun",
  "Sabah Suları",
  "Ben'le",
  "Acıya Bak",
  "ahh Kelimeler",
  "Devam Yola",
  "Eskiz",
  "Felaket",
  "Lale Sarhoş",
  "Manşet",
  "Pusula'm",
  "Rastlantı",
  "'Seç'tim",
  "Lorem Ipsum",
  "Luna-Park",
  "Kamp Hali",
  "Yaz Beni",
  "Gel-ecek",
  "LİCNEB ANAS",
  "İmza",
  "Emek",
  "Bilinçaltım Uyardı",
  "Düşler Prensi",
  "İlham",
  "Su Kurbağası",
  "Hikmet",
  "Bazense Susmak",
] as const;

/** Kitaptaki deneme başlıkları (sıra ile) */
export const ESSAY_TITLES = [
  "Birden Bine",
  "Cenaze Dolayısıyla Kapalıyız",
  "Ne Desem Bilemedim",
  "Anlatmıştım Yetmemişti",
  "Mektup",
  "Bazen Her Zaman",
  "Gönül",
  "Kırık Camlar",
  "Mavi Önlük Beyaz Yaka",
  "Meyuslardan Yazıtlar",
  "İnsanların Arasında 'Tanrı' Yalnızlığı",
] as const;
